In [1]:
import pandas as pd
import numpy as np

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
s1 = pd.Series(range(10))

In [5]:
s1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [6]:
s1.count()

10

In [7]:
s1[3]

3

In [9]:
np.nan

nan

In [10]:
s1[3] = np.nan

In [11]:
s1

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [12]:
s1.count()

9

In [13]:
np.random.seed(2)

In [15]:
np.random.randint(5, size=(4,4))

array([[0, 3, 2, 3],
       [0, 2, 1, 3],
       [2, 4, 4, 4],
       [3, 4, 2, 3]])

In [16]:
df = pd.DataFrame(np.random.randint(5, size=(4,4)), dtype=float)

In [17]:
df

0    1    2    3
0  3.0  2.0  1.0  2.0
1  4.0  3.0  0.0  4.0
2  3.0  1.0  2.0  0.0
3  4.0  4.0  2.0  4.0

In [18]:
df.iloc[2,3]

0.0

In [19]:
df.iloc[2,3] = np.nan

In [20]:
df.iloc[2,3]

nan

In [21]:
df

0    1    2    3
0  3.0  2.0  1.0  2.0
1  4.0  3.0  0.0  4.0
2  3.0  1.0  2.0  NaN
3  4.0  4.0  2.0  4.0

In [22]:
df.count()

0    4
1    4
2    4
3    3
dtype: int64

In [23]:
np.random.randint(6, size=100)

array([2, 1, 0, 2, 5, 2, 1, 5, 0, 1, 0, 2, 5, 1, 1, 1, 4, 2, 3, 0, 3, 0,
       2, 2, 0, 4, 2, 0, 2, 4, 1, 5, 3, 0, 2, 1, 4, 0, 1, 5, 1, 5, 5, 1,
       2, 4, 2, 3, 4, 5, 2, 0, 2, 3, 3, 0, 0, 5, 3, 5, 3, 5, 0, 0, 2, 5,
       3, 1, 5, 2, 3, 4, 3, 3, 1, 4, 2, 3, 0, 0, 2, 5, 4, 4, 3, 2, 1, 1,
       1, 2, 1, 3, 0, 1, 0, 4, 3, 1, 3, 0])

In [25]:
s2 = pd.Series(np.random.randint(6, size=100))

In [26]:
s2

0     5
1     1
2     4
3     1
4     0
     ..
95    2
96    3
97    3
98    2
99    3
Length: 100, dtype: int32

In [27]:
s2.tail()

95    2
96    3
97    3
98    2
99    3
dtype: int32

In [28]:
s2.head()

0    5
1    1
2    4
3    1
4    0
dtype: int32

In [29]:
s2.value_counts()

2    23
3    22
4    17
1    16
5    13
0     9
dtype: int64

In [30]:
df

0    1    2    3
0  3.0  2.0  1.0  2.0
1  4.0  3.0  0.0  4.0
2  3.0  1.0  2.0  NaN
3  4.0  4.0  2.0  4.0

In [31]:
df.value_counts()

AttributeError: 'DataFrame' object has no attribute 'value_counts'

In [32]:
df[0]

0    3.0
1    4.0
2    3.0
3    4.0
Name: 0, dtype: float64

In [33]:
type(df[0])

pandas.core.series.Series

In [34]:
df[0].value_counts()

4.0    2
3.0    2
Name: 0, dtype: int64

In [35]:
np.random.seed(1)

In [36]:
np.random.randint(6, size=100)

array([5, 3, 4, 0, 1, 3, 5, 0, 0, 1, 4, 5, 4, 1, 2, 4, 5, 2, 4, 3, 4, 2,
       4, 5, 2, 4, 1, 1, 0, 5, 1, 1, 5, 1, 1, 0, 4, 1, 0, 0, 5, 3, 2, 1,
       0, 3, 5, 1, 1, 3, 4, 0, 1, 3, 4, 2, 4, 0, 5, 3, 1, 2, 0, 4, 1, 2,
       2, 1, 0, 1, 3, 5, 4, 3, 5, 1, 3, 0, 0, 2, 2, 1, 3, 4, 2, 0, 0, 1,
       1, 5, 3, 0, 0, 5, 5, 4, 5, 2, 4, 3])

In [37]:
s1 = pd.Series(np.random.randint(6, size=100))

In [38]:
s1

0     5
1     3
2     5
3     0
4     3
     ..
95    5
96    3
97    4
98    2
99    0
Length: 100, dtype: int32

In [39]:
s1.value_counts()

5    20
4    19
0    19
1    17
2    15
3    10
dtype: int64

In [40]:
s1.value_counts().sort_index()

0    19
1    17
2    15
3    10
4    19
5    20
dtype: int64

In [42]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
s2 = pd.Series(range(10))

In [44]:
s2

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [45]:
s2[3]

3

In [47]:
s2[3] = np.nan

In [48]:
s2[3] 

nan

In [49]:
s2

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [50]:
s2.sort_values()

0    0.0
1    1.0
2    2.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
3    NaN
dtype: float64

In [51]:
s2.sort_values(ascending=True)

0    0.0
1    1.0
2    2.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
3    NaN
dtype: float64

In [52]:
s2.sort_values(ascending=False)

9    9.0
8    8.0
7    7.0
6    6.0
5    5.0
4    4.0
2    2.0
1    1.0
0    0.0
3    NaN
dtype: float64