In [1]:
import pandas as pd
import numpy as np

In [3]:
np.random.seed(2)

In [6]:
np.random.randint(5, size=(4,4))

array([[3, 3, 2, 1],
       [2, 4, 3, 0],
       [4, 3, 1, 2],
       [0, 4, 4, 2]])

In [4]:
df = pd.DataFrame(np.random.randint(5, size=(4,4)), 
                  dtype=float)

In [5]:
df

0    1    2    3
0  0.0  0.0  3.0  2.0
1  3.0  0.0  2.0  1.0
2  3.0  2.0  4.0  4.0
3  4.0  3.0  4.0  2.0

In [7]:
df.sort_values(by=2)

0    1    2    3
1  3.0  0.0  2.0  1.0
0  0.0  0.0  3.0  2.0
2  3.0  2.0  4.0  4.0
3  4.0  3.0  4.0  2.0

In [8]:
df.sort_values(by=[2, 3, 0])

0    1    2    3
1  3.0  0.0  2.0  1.0
0  0.0  0.0  3.0  2.0
3  4.0  3.0  4.0  2.0
2  3.0  2.0  4.0  4.0

In [9]:
np.random.seed(1)

In [11]:
np.random.randint(10, size=(4, 8))

array([[8, 9, 5, 0, 0, 1, 7, 6],
       [9, 2, 4, 5, 2, 4, 2, 4],
       [7, 7, 9, 1, 7, 0, 6, 9],
       [9, 7, 6, 9, 1, 0, 1, 8]])

In [12]:
df = pd.DataFrame(np.random.randint(10, size=(4, 8)))

In [13]:
df

0  1  2  3  4  5  6  7
0  8  3  9  8  7  3  6  5
1  1  9  3  4  8  1  4  0
2  3  9  2  0  4  9  2  7
3  7  9  8  6  9  3  7  7

In [14]:
df.sum(axis=1)

0    49
1    30
2    36
3    56
dtype: int64

In [15]:
df.sum(axis=0)

0    19
1    30
2    22
3    18
4    28
5    16
6    19
7    19
dtype: int64

In [16]:
df.sum(axis=1)

0    49
1    30
2    36
3    56
dtype: int64

In [17]:
df['RowSum'] = df.sum(axis=1)

In [18]:
df['RowSum']

0    49
1    30
2    36
3    56
Name: RowSum, dtype: int64

In [19]:
df

0  1  2  3  4  5  6  7  RowSum
0  8  3  9  8  7  3  6  5      49
1  1  9  3  4  8  1  4  0      30
2  3  9  2  0  4  9  2  7      36
3  7  9  8  6  9  3  7  7      56

In [20]:
df.sum()

0          19
1          30
2          22
3          18
4          28
5          16
6          19
7          19
RowSum    171
dtype: int64

In [21]:
df.sum(axis=0)

0          19
1          30
2          22
3          18
4          28
5          16
6          19
7          19
RowSum    171
dtype: int64

In [23]:
df['RowSum']

0    49
1    30
2    36
3    56
Name: RowSum, dtype: int64

In [24]:
df['ColTotal']

KeyError: 'ColTotal'

In [25]:
df.loc[2, :]

0          3
1          9
2          2
3          0
4          4
5          9
6          2
7          7
RowSum    36
Name: 2, dtype: int64

In [26]:
df.loc['ColTotal', :] = df.sum()

In [27]:
df

0     1     2     3     4     5     6     7  RowSum
0          8.0   3.0   9.0   8.0   7.0   3.0   6.0   5.0    49.0
1          1.0   9.0   3.0   4.0   8.0   1.0   4.0   0.0    30.0
2          3.0   9.0   2.0   0.0   4.0   9.0   2.0   7.0    36.0
3          7.0   9.0   8.0   6.0   9.0   3.0   7.0   7.0    56.0
ColTotal  19.0  30.0  22.0  18.0  28.0  16.0  19.0  19.0   171.0

In [28]:
df = pd.DataFrame({
    'A':[1, 3, 4, 3, 4],
    'B':[2, 3, 1, 2, 3],
    'C':[1, 5, 2, 4, 4]
})

In [29]:
df

A  B  C
0  1  2  1
1  3  3  5
2  4  1  2
3  3  2  4
4  4  3  4

In [30]:
def num(x):
    return x.max() - x.min()

In [31]:
result = df.apply(num)

In [32]:
result

A    3
B    2
C    4
dtype: int64

In [33]:
result = df.apply(lambda x: x.max() - x.min())

In [34]:
result

A    3
B    2
C    4
dtype: int64

In [35]:
result = df.apply(num, axis=1)

In [36]:
result

0    1
1    2
2    3
3    2
4    1
dtype: int64

In [37]:
df

A  B  C
0  1  2  1
1  3  3  5
2  4  1  2
3  3  2  4
4  4  3  4

In [38]:
result = df.apply(pd.value_counts)

In [39]:
result

A    B    C
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

In [40]:
result = df.apply(pd.value_counts).fillna(0)

In [41]:
result

A    B    C
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [ ]:
# 결측치 제거 -> 데이터 전처리

In [46]:
result = df.apply(pd.value_counts).fillna(0).astype(int)

In [47]:
result

A  B  C
1  1  1  1
2  0  2  1
3  2  2  0
4  2  0  2
5  0  0  1

In [48]:
ages = [0, 2, 10, 21, 23, 37, 31, 61, 20, 41, 32, 100]

In [49]:
ages

[0, 2, 10, 21, 23, 37, 31, 61, 20, 41, 32, 100]

In [59]:
bins = [1, 15, 25, 35, 60, 90]

In [51]:
bins

[1, 15, 25, 35, 60, 90]

In [52]:
labels = ['미성년자', '청년', '중년', '장년', '노년']

In [53]:
labels

['미성년자', '청년', '중년', '장년', '노년']

In [60]:
result = pd.cut(ages, bins=bins, labels=labels)

In [61]:
result

[NaN, 미성년자, 미성년자, 청년, 청년, ..., 노년, 청년, 장년, 중년, NaN]
Length: 12
Categories (5, object): [미성년자 < 청년 < 중년 < 장년 < 노년]

In [62]:
type(result)

pandas.core.arrays.categorical.Categorical

In [63]:
result.categories

Index(['미성년자', '청년', '중년', '장년', '노년'], dtype='object')

In [64]:
result.codes

array([-1,  0,  0,  1,  1,  3,  2,  4,  1,  3,  2, -1], dtype=int8)

In [65]:
df = pd.DataFrame(ages, columns=['ages'])

In [66]:
df

ages
0      0
1      2
2     10
3     21
4     23
5     37
6     31
7     61
8     20
9     41
10    32
11   100

In [67]:
df.ages

0       0
1       2
2      10
3      21
4      23
5      37
6      31
7      61
8      20
9      41
10     32
11    100
Name: ages, dtype: int64

In [68]:
df['age_cat'] = pd.cut(df.ages, bins=bins, labels=labels)

In [69]:
df

ages age_cat
0      0     NaN
1      2    미성년자
2     10    미성년자
3     21      청년
4     23      청년
5     37      장년
6     31      중년
7     61      노년
8     20      청년
9     41      장년
10    32      중년
11   100     NaN

In [70]:
data = np.random.randn(1000)

In [71]:
data

array([ 6.77097876e-02, -1.03890593e+00, -2.63677447e-01,  5.38250569e-01,
        1.52826025e+00,  1.95667685e+00,  4.78200352e-01,  1.19345210e-01,
       -8.57465206e-01, -7.61947804e-01,  6.39304899e-01,  4.75260532e-02,
        3.11483365e+00, -5.32461593e-01,  3.45583676e-01, -4.25514043e-01,
       -2.23877138e+00,  1.75539696e+00, -2.64193363e-01,  8.46294467e-01,
        2.08673250e+00,  5.26478312e-01,  9.83809002e-01, -1.92220001e+00,
       -8.94825229e-01,  3.30062822e-01,  1.04859100e+00,  1.34989935e+00,
        1.24567511e+00, -6.91191472e-01,  1.28107338e+00, -7.27064310e-01,
       -7.99168694e-01, -3.54562185e-03,  5.12594636e-01, -1.67860864e-01,
        1.34633628e+00, -6.15491978e-01, -7.43036696e-01,  1.01593613e+00,
       -5.55155414e-01,  4.36259361e-01, -1.46689715e-01,  2.34928244e-02,
       -2.58302186e-01,  1.83915619e+00, -1.93989588e-01,  1.57413147e+00,
        7.56900469e-01, -5.27124266e-01, -7.53429475e-01,  8.99466368e-02,
        1.68171225e+00, -

In [72]:
result = pd.qcut(data, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [73]:
result

[Q3, Q1, Q2, Q3, Q4, ..., Q2, Q4, Q4, Q4, Q4]
Length: 1000
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [74]:
result1 = pd.value_counts(result)

In [75]:
result1

Q4    250
Q3    250
Q2    250
Q1    250
dtype: int64