In [1]:
import numpy as np
import pandas as pd

In [2]:
s1 = pd.Series([0, 1], index=['A', 'B'])

In [3]:
s1

A    0
B    1
dtype: int64

In [4]:
s2 = pd.Series([2, 3, 4], index=['A', 'B', 'C'])

In [5]:
s2

A    2
B    3
C    4
dtype: int64

In [6]:
result = pd.concat([s1, s2])

In [7]:
result

A    0
B    1
A    2
B    3
C    4
dtype: int64

In [8]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [10]:
np.arange(6).reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), 
                  columns=['데이터1', '데이터2'],
                  index=['a', 'b', 'c'])

In [12]:
df1

데이터1  데이터2
a     0     1
b     2     3
c     4     5

In [13]:
np.arange(4)

array([0, 1, 2, 3])

In [14]:
5 + np.arange(4)

array([5, 6, 7, 8])

In [15]:
5 + np.arange(4).reshape(2, 2)

array([[5, 6],
       [7, 8]])

In [16]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), 
                  columns=['데이터3', '데이터4'],
                  index=['a', 'c'])

In [17]:
df2

데이터3  데이터4
a     5     6
c     7     8

In [18]:
result = pd.concat([df1, df2], axis=1, sort=False)

In [19]:
result

데이터1  데이터2  데이터3  데이터4
a     0     1   5.0   6.0
b     2     3   NaN   NaN
c     4     5   7.0   8.0