In [3]:
import numpy

In [4]:
numpy.sqrt(2)

1.4142135623730951

In [5]:
import numpy as np

In [6]:
np.sqrt(2)

1.4142135623730951

In [7]:
np.pi

3.141592653589793

In [8]:
np.cos(np.pi)

-1.0

In [11]:
numbers = np.array(range(1, 11), copy=True )

In [12]:
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
numbers.ndim

1

In [15]:
numbers.shape

(10,)

In [16]:
numbers.dtype

dtype('int32')

In [17]:
print(type(numbers))

<class 'numpy.ndarray'>


In [19]:
list = [10, 20, 30, 40]

In [20]:
nparra = np.array(list)

In [21]:
print(type(nparra))

<class 'numpy.ndarray'>


In [22]:
print(nparra)

[10 20 30 40]


In [23]:
print(nparra.shape)

(4,)


In [24]:
nparrb = np.array([[10, 20, 30], [40, 50, 60]])

In [25]:
print(nparrb.shape)

(2, 3)


In [26]:
print(nparrb)

[[10 20 30]
 [40 50 60]]


In [27]:
print(nparrb[0, 0])

10


In [28]:
print(nparrb[1, 2])

60


In [29]:
a = np.array([10, 20, 30, 40])

In [30]:
print(a)

[10 20 30 40]


In [31]:
b = [50, 60, 70, 80]

In [32]:
print(b)

[50, 60, 70, 80]


In [33]:
print(type(a))

<class 'numpy.ndarray'>


In [34]:
print(type(b))

<class 'list'>


In [35]:
print(a[1], a[-1])

20 40


In [36]:
print(a[1:])

[20 30 40]


In [37]:
a = np.array([10, 20, '30', 40])

In [38]:
print(a)

['10' '20' '30' '40']


In [39]:
a = np.zeros(10)

In [40]:
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [41]:
a = np.ones(10)

In [42]:
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [43]:
a = np.eye(3)

In [44]:
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
