In [1]:
import numpy as np

In [2]:
eye = np.eye(3)

In [3]:
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
print(eye.dtype)

float64


In [7]:
eye = eye.astype(np.int)

In [8]:
print(eye.dtype)

int32


In [9]:
print(eye)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [10]:
eye_copy = eye.copy()

In [11]:
print(eye_copy)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
