In [1]:
import numpy as np

In [11]:
x = np.array([10, 20, 30])

In [3]:
print(type(x))

<class 'numpy.ndarray'>


In [12]:
print(x)

[10 20 30]


In [4]:
print(x.dtype)

int32


In [5]:
x = np.array([1.0, 2.0, 3.0])

In [6]:
print(x)

[1. 2. 3.]


In [7]:
print(x.dtype)

float64


In [8]:
x = np.array([10, 20, 3.0])

In [9]:
print(x)

[10. 20.  3.]


In [10]:
print(x.dtype)

float64


In [13]:
x = np.array([10, 20, 30], dtype='f')

In [14]:
print(x)

[10. 20. 30.]


In [15]:
print(x.dtype)

float32


In [16]:
print(x[0] + x[2])

40.0


In [17]:
x = np.array([1, 2, 3], dtype='U')

In [18]:
print(x)

['1' '2' '3']


In [19]:
print(x.dtype)

<U1
