In [1]:
import numpy as np

In [2]:
data = np.array(7) / np.array(1)

In [3]:
print(data)

7.0


In [4]:
data = np.array(7) / np.array(0)

C:\Users\TJ\Anaconda3\envs\codelab\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [5]:
print(data)

inf


In [8]:
data = np.array([7, 1, -1, 10]) / np.array([1, 0, 0, 0])

C:\Users\TJ\Anaconda3\envs\codelab\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [9]:
print(data)

[  7.  inf -inf  inf]


In [10]:
data = np.log(0)

C:\Users\TJ\Anaconda3\envs\codelab\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [11]:
print(data)

-inf


In [12]:
print(np.inf)

inf


In [13]:
print(-np.inf)

-inf


In [16]:
data = np.array([0, 0, -0, 0]) / np.array([1, 0, 0, 0])

C:\Users\TJ\Anaconda3\envs\codelab\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [17]:
print(data)

[ 0. nan nan nan]


In [18]:
a = np.zeros(5)

In [19]:
print(a)

[0. 0. 0. 0. 0.]


In [20]:
a = np.zeros((2, 2))

In [21]:
print(a)

[[0. 0.]
 [0. 0.]]


In [24]:
a = np.zeros( (5, 2) , dtype='i')

In [25]:
print(a)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [26]:
a = np.zeros(5, dtype='U4')

In [27]:
print(a)

['' '' '' '' '']


In [28]:
a[0]='A'

In [29]:
a[1]='B'

In [30]:
a[2]='C'

In [35]:
a[3]='DEFGHIJK'

In [36]:
a[4]='ABCDEF'

In [37]:
print(a)

['A' 'B' 'C' 'DEFG' 'ABCD']


In [38]:
b = np.ones(3)

In [39]:
print(b)

[1. 1. 1.]


In [40]:
b = np.ones( (2, 3) )

In [41]:
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [44]:
b = np.ones( (2, 3, 4))

In [45]:
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [46]:
a = np.zeros( (2,3) )

In [47]:
b = np.ones_like(a)

In [48]:
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [51]:
c = np.empty( (4, 3) )

In [52]:
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [53]:
d = np.arange(10)

In [54]:
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [57]:
d = np.arange(3, 21, 2)

In [58]:
print(d)

[ 3  5  7  9 11 13 15 17 19]


In [59]:
e = np.linspace(0, 100, 5)

In [60]:
print(e)

[  0.  25.  50.  75. 100.]


In [61]:
e = np.logspace(0, 100, 5)

In [62]:
print(e)

[1.e+000 1.e+025 1.e+050 1.e+075 1.e+100]


In [66]:
f = np.full( (3,2) , 5 )

In [67]:
print(f)

[[5 5]
 [5 5]
 [5 5]]


In [68]:
h = np.eye(3)

In [69]:
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [76]:
arr = np.array([[0, 1, 2], [3, 4, 5]])

In [77]:
print(arr)

[[0 1 2]
 [3 4 5]]


In [78]:
print(len(arr))

2


In [82]:
print(len(arr[1]))

3


In [81]:
print(arr[1])

[3 4 5]


In [73]:
arr = np.array([0, 1, 2])

In [74]:
print(arr)

[0 1 2]


In [75]:
print(len(arr))

3


In [83]:
arr = np.array( [[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
               [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]]
              )

In [84]:
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [91]:
print(len(arr[0][0]))

4


In [88]:
print(len(arr[0]))

3


In [85]:
print(len(arr))

2


In [92]:
arr1 = np.array([10, 20, 30])

In [93]:
print(arr1.ndim)

1


In [94]:
print(arr1.shape)

(3,)


In [105]:
arr2 = np.array( [[0, 1, 2],[3, 4, 5]])

In [106]:
print(arr2)

[[0 1 2]
 [3 4 5]]


In [103]:
print(arr2.ndim)

2


In [107]:
print(arr2.shape)

(2, 3)


In [108]:
arr3 = np.array([ [[0, 1, 2],[3, 4, 5]], 
                [[6, 7, 8],[9, 10, 11]] ])

In [109]:
print(arr3)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [110]:
print(arr3.ndim)

3


In [111]:
print(arr3.shape)

(2, 2, 3)


In [112]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
idx = np.array([True, False, True, False, True, False, True, False, True, False])

In [114]:
result = arr[idx]

In [115]:
print(result)

[0 2 4 6 8]


In [116]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [117]:
result1 = arr%2

In [118]:
print(result1)

[0 1 0 1 0 1 0 1 0 1]


In [119]:
result2 = arr%2==0

In [120]:
print(result2)

[ True False  True False  True False  True False  True False]


In [122]:
print(arr[result2])

[0 2 4 6 8]


In [123]:
print(arr[arr%2==0])

[0 2 4 6 8]
