In [6]:
import numpy as np

In [1]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
print(data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [2]:
answer = []

In [3]:
for di in data:
    answer.append(di*3)

In [4]:
print(answer)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]


In [7]:
x = np.array(data)

In [8]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
result = x*3

In [11]:
print(result)

[ 0  3  6  9 12 15 18 21 24 27]


In [12]:
a = np.array([1, 2, 3, 4, 5])

In [13]:
b = np.array([10, 20, 30, 40, 50])

In [14]:
result = 2*a+b

In [15]:
print(result)

[12 24 36 48 60]


In [16]:
print(a)

[1 2 3 4 5]


In [17]:
result = a == 2

In [18]:
print(result)

[False  True False False False]


In [19]:
print(b)

[10 20 30 40 50]


In [20]:
result = b>10

In [21]:
print(result)

[False  True  True  True  True]


In [22]:
result = (a==2) & (b>10)

In [23]:
print(result)

[False  True False False False]


In [24]:
data = np.array( [[10, 20, 30], [40, 50, 60]]  )

In [25]:
print(data)

[[10 20 30]
 [40 50 60]]


In [30]:
print(data.shape)

(2, 3)


In [26]:
dataT = data.T

In [27]:
print(dataT)

[[10 40]
 [20 50]
 [30 60]]


In [29]:
print(dataT.shape)

(3, 2)


In [31]:
data = np.arange(12)

In [32]:
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [33]:
data_reshape = data.reshape(3, 4)

In [34]:
print(data_reshape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
data_reshape = data.reshape(3, -1)

In [36]:
print(data_reshape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
data_reshape = data.reshape(2, 2, -1)

In [38]:
print(data_reshape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [39]:
data_reshape = data.reshape(2, -1, 2)

In [40]:
print(data_reshape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
