In [1]:
import numpy as np

In [ ]:
0 부터 순차적으로 증가는 20개의 값을 가진 -> range()
-> np 배열
4행 5열의 배열 만들기 -> np.reshape()

In [4]:
result = np.array(range(20)) .reshape((4, 5))

In [5]:
print(result)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [6]:
x = np.arange(7)

In [7]:
print(x)

[0 1 2 3 4 5 6]


In [8]:
x.reshape(1, 7)

array([[0, 1, 2, 3, 4, 5, 6]])

In [9]:
result = x.reshape(7, 1)

In [10]:
print(result)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [11]:
print(x)

[0 1 2 3 4 5 6]


In [12]:
lst= [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [13]:
arr = np.array(lst)

In [14]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
result = arr[1, 0]

In [18]:
print(result)

4


In [19]:
result = arr[0, :]

In [20]:
print(result)

[1 2 3]


In [21]:
result = arr[:, 1]

In [22]:
print(result)

[2 5 8]


In [23]:
result = arr[1, 1:]

In [24]:
print(result)

[5 6]


In [25]:
result = arr[0:2, 0:2]

In [26]:
print(result)

[[1 2]
 [4 5]]


In [27]:
result = arr[1:, 1:]

In [28]:
print(result)

[[5 6]
 [8 9]]


In [29]:
arr = np.array([0, 1, 2, 3, 4])

In [30]:
print(arr[2])

2


In [31]:
print(arr[-1])

4


In [32]:
print(arr[-4])

1


In [33]:
print(arr[6])

IndexError: index 6 is out of bounds for axis 0 with size 5

In [34]:
lst=[
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]

In [35]:
a = np.array(lst)

In [36]:
print(a[0, 2])

3


In [37]:
print(a[1, 3])

8


In [38]:
result = a[[0, 2], [1, 3]]

In [39]:
print(result)

[ 2 12]


In [40]:
result = a[-1, -1]

In [41]:
print(result)

12


In [42]:
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [43]:
a = np.array(lst)

In [44]:
bool_indexing_array = np.array( [
    [False, True, False],
    [True, False, True],
    [False, True, False]
] )

In [45]:
print(bool_indexing_array)

[[False  True False]
 [ True False  True]
 [False  True False]]


In [46]:
n = a[bool_indexing_array]

In [47]:
print(n)

[2 4 6 8]


In [48]:
bool_indexing = a%2==0

In [49]:
print(bool_indexing)

[[False  True False]
 [ True False  True]
 [False  True False]]


In [52]:
result = a[bool_indexing]

In [53]:
print(result)

[2 4 6 8]


In [54]:
result = a[a%2==0]

In [55]:
print(result)

[2 4 6 8]


In [60]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
print(bool_indexing)

[[False  True False]
 [ True False  True]
 [False  True False]]


In [62]:
a[bool_indexing] = 10

In [63]:
print(a)

[[ 1 10  3]
 [10  5 10]
 [ 7 10  9]]


In [ ]:
절대음수가 될 수 없다고 가정
음수값은 진짜값이 아닌 오류
오류(결측치)인 음수값을 0으로 바꾸기
-> 데이터 클리닝, 데이터 정제, 데이터 전처리

불린 인덱스 배열

In [58]:
dirty = np.array([9, 4, 1, -0.01, -0.02, -0.001])

In [59]:
print(dirty)

[ 9.e+00  4.e+00  1.e+00 -1.e-02 -2.e-02 -1.e-03]


In [64]:
whos_dirty = dirty < 0

In [65]:
print(whos_dirty)

[False False False  True  True  True]


In [67]:
dirty[whos_dirty]=0

In [68]:
print(dirty)

[9. 4. 1. 0. 0. 0.]
