In [2]:
import numpy as np

In [3]:
linear = np.arange(-1, 1.1, 0.2)

In [4]:
print(linear)

[-1.00000000e+00 -8.00000000e-01 -6.00000000e-01 -4.00000000e-01
 -2.00000000e-01 -2.22044605e-16  2.00000000e-01  4.00000000e-01
  6.00000000e-01  8.00000000e-01  1.00000000e+00]


In [ ]:
불린인덱스배열 -> 특정 범위의 데이터 확인
-0.5와 0.5사이에 위치한 데이터요소가 무엇인지 출력

-0.5와 0.5사이 -> True

In [5]:
linear_boolean = (linear <=0.5) & (linear >= -0.5)

In [6]:
print(linear_boolean)

[False False False  True  True  True  True  True False False False]


In [7]:
result = linear[linear_boolean]

In [8]:
print(result)

[-4.00000000e-01 -2.00000000e-01 -2.22044605e-16  2.00000000e-01
  4.00000000e-01]


In [9]:
a = np.arange(4)

In [10]:
print(a)

[0 1 2 3]


In [11]:
b= np.arange(1, 5)

In [12]:
print(b)

[1 2 3 4]


In [13]:
result = a + b

In [14]:
print(result)

[1 3 5 7]


In [16]:
[0+1 1+2 2+3 3+4]

In [17]:
result = a*5

In [18]:
print(result)

[ 0  5 10 15]


In [19]:
print( np.eye(4) ) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
print( np.ones(4,) )

[1. 1. 1. 1.]


In [21]:
print( 0.01* np.ones(4,) )

[0.01 0.01 0.01 0.01]


In [22]:
result = np.eye(4) + 0.01* np.ones(4,)

In [23]:
print(result)

[[1.01 0.01 0.01 0.01]
 [0.01 1.01 0.01 0.01]
 [0.01 0.01 1.01 0.01]
 [0.01 0.01 0.01 1.01]]


In [24]:
a = np.array([1, 2, 3])

In [25]:
b = np.array([4, 5, 6])

In [26]:
print(a)

[1 2 3]


In [27]:
print(b)

[4 5 6]


In [28]:
c = a + b

In [29]:
print(c)

[5 7 9]


In [30]:
c = np.add(a, b)

In [31]:
print(c)

[5 7 9]


In [34]:
print(np.add(a, b))

[5 7 9]


In [35]:
c = np.add(a, b)
c

array([5, 7, 9])

In [36]:
np.add(a, b)

array([5, 7, 9])

In [32]:
c = a - b

In [33]:
print(c)

[-3 -3 -3]


In [37]:
c = np.subtract(a, b)

In [38]:
print(c)

[-3 -3 -3]


In [39]:
c = a * b

In [40]:
print(c)

[ 4 10 18]


In [41]:
c = np.multiply(a, b)

In [42]:
print(c)

[ 4 10 18]


In [44]:
c = a / b

In [45]:
print(c)

[0.25 0.4  0.5 ]


In [46]:
c = np.divide(a, b)

In [47]:
print(c)

[0.25 0.4  0.5 ]


In [48]:
lst1 = [
    [1, 2],
    [3, 4]
]

In [49]:
lst2 = [
    [5, 6],
    [7, 8]
]

In [50]:
a = np.array(lst1)

In [51]:
b = np.array(lst2)

In [52]:
c = np.dot(a, b)

In [53]:
print(c)

[[19 22]
 [43 50]]


In [ ]:
[1*5+ 2*7],   [1*6+ 2*8]
[3*5+ 4*7],   [3*6+ 4*8]

In [54]:
[5, 6],
[7, 8]

[7, 8]

In [55]:
lst1 = [
    [1, 4],
    [2, 5],
    [3, 6]
]

In [56]:
a = np.array(lst1)

In [57]:
print(a)

[[1 4]
 [2 5]
 [3 6]]


In [58]:
lst2 = [
    [7, 8, 9],
    [10, 11, 12]
]

In [59]:
b = np.array(lst2)

In [60]:
print(b)

[[ 7  8  9]
 [10 11 12]]


In [61]:
c = np.dot(a, b)

In [62]:
print(c)

[[47 52 57]
 [64 71 78]
 [81 90 99]]


In [ ]:
[1*7+4*10]      [1*8+4*11]     [1*9+4*12]
[2*7+5*10]      [2*8+5*11]     [2*9+5*12]
[3*7+6*10]      [3*8+6*11]     [3*9+6*12]

In [63]:
a = np.array([
    [1,2],
    [3,4]
])

In [64]:
print(a)

[[1 2]
 [3 4]]


In [65]:
s = np.sum(a)

In [66]:
print(s)

10


In [67]:
s = np.sum(a, axis=0)

In [68]:
print(s)

[4 6]


In [69]:
s = np.sum(a, axis=1)

In [70]:
print(s)

[3 7]


In [71]:
s = np.prod(a)

In [72]:
print(s)

24


In [73]:
s = np.prod(a, axis=0)

In [74]:
print(s)

[3 8]


In [75]:
s = np.prod(a, axis=1)

In [76]:
print(s)

[ 2 12]


In [77]:
data = np.arange(12)

In [78]:
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [79]:
data_reshape = data.reshape(3, -1, 2)

In [80]:
print(data_reshape)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [ ]:
flatten()
다차원 -> 무조건 1차원

In [81]:
data_flatten = data_reshape.flatten()

In [82]:
print(data_flatten)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [83]:
data = np.arange(12)

In [84]:
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [85]:
data_newaxis = data[:,np.newaxis]

In [86]:
print(data_newaxis)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [87]:
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [88]:
data_newaxis = data[np.newaxis,:]

In [89]:
print(data_newaxis)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [90]:
x = np.arange(3)

In [91]:
print(x)

[0 1 2]


In [92]:
y = np.arange(5)

In [93]:
print(y)

[0 1 2 3 4]


In [94]:
xy = np.meshgrid(x, y)

In [95]:
print(xy)

[array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]]), array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])]


In [96]:
xx, yy = np.meshgrid(x, y)

In [97]:
print(xx)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]


In [98]:
print(yy)

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [99]:
result = zip(xx, yy)

In [100]:
print(result)

In [101]:
rst = [list(zip(x, y)) for x, y in zip(xx, yy)]

In [102]:
print(rst)

[[(0, 0), (1, 0), (2, 0)], [(0, 1), (1, 1), (2, 1)], [(0, 2), (1, 2), (2, 2)], [(0, 3), (1, 3), (2, 3)], [(0, 4), (1, 4), (2, 4)]]
