In [1]:
import numpy as np

In [2]:
np.random.seed(3)

In [3]:
result = np.random.rand(5)

In [4]:
result

array([0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695])

In [5]:
result = np.random.rand(5)

In [6]:
result

array([0.89629309, 0.12558531, 0.20724288, 0.0514672 , 0.44080984])

In [7]:
result = np.random.rand(5)

In [8]:
result

array([0.02987621, 0.45683322, 0.64914405, 0.27848728, 0.6762549 ])

In [9]:
type(result)

numpy.ndarray

In [10]:
from datetime import datetime

In [22]:
dt = datetime.now()

In [12]:
dt

datetime.datetime(2020, 2, 3, 12, 9, 24, 818839)

In [23]:
seednum = dt.microsecond

In [14]:
seednum

818839

In [24]:
np.random.seed(seednum)

In [25]:
result = np.random.rand(5)

In [26]:
result

array([0.62114208, 0.49290279, 0.45468426, 0.25396308, 0.08797138])

In [27]:
result = np.random.rand(10)

In [28]:
result

array([0.87755956, 0.12292519, 0.86092795, 0.66274028, 0.0796688 ,
       0.95673099, 0.64389768, 0.29992018, 0.1774132 , 0.04066948])

In [29]:
result = np.random.rand(3, 5)

In [30]:
result

array([[0.94048155, 0.32092423, 0.05031826, 0.85050259, 0.98532236],
       [0.86212717, 0.95158411, 0.17712355, 0.0751971 , 0.5420802 ],
       [0.8087867 , 0.58743345, 0.72421549, 0.89573087, 0.55132921]])

In [31]:
result = np.random.randn(10)

In [32]:
result

array([ 0.72511206, -0.59129747,  1.09034271,  0.47282156, -2.20683601,
        0.10541735, -1.19941148, -2.18845201,  2.344412  , -0.33520985])

In [33]:
result = np.random.randn(3, 5)

In [34]:
result

array([[ 0.43600047, -0.05613182,  0.66816144, -2.32747854, -0.78065463],
       [ 1.13651262,  0.32382485,  0.31768305,  0.82504128,  0.92602508],
       [-0.6189976 ,  1.73526456,  0.14448869,  0.63626238, -1.83662287]])

In [35]:
result = np.random.randint(10, size=10)

In [36]:
result

array([2, 2, 8, 6, 6, 9, 5, 7, 7, 8])

In [37]:
result = np.random.randint(10, 20, size=10)

In [38]:
result

array([17, 11, 11, 13, 10, 12, 15, 13, 19, 14])

In [39]:
result = np.random.randint(10, 20, size=(3,5))

In [40]:
result

array([[13, 17, 16, 14, 16],
       [10, 12, 19, 18, 15],
       [18, 15, 14, 15, 14]])

In [41]:
data = np.arange(10)

In [42]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.random.shuffle(data)

In [50]:
data

array([8, 1, 7, 9, 5, 4, 2, 0, 3, 6])

In [51]:
result = np.random.choice(5, 5, replace=False)

In [52]:
result

array([1, 0, 2, 3, 4])

In [53]:
result = np.random.choice(5, 3, replace=False)

In [54]:
result

array([3, 2, 0])

In [55]:
result = np.random.choice(5, 10)

In [56]:
result

array([1, 3, 2, 0, 4, 1, 4, 3, 4, 2])

In [61]:
result = np.random.choice(5, 10, p=[0.1, 0, 0.3,0.6, 0])

In [62]:
result

array([3, 2, 2, 3, 0, 3, 2, 3, 3, 2])