In [1]:
import numpy as np

In [2]:
data = [11, 11, 12, 2, 34, 34]

In [3]:
result = np.unique(data)

In [4]:
result

array([ 2, 11, 12, 34])

In [7]:
data = np.array(['a', 'b', 'b', 'c', 'a'])

In [8]:
data

array(['a', 'b', 'b', 'c', 'a'], dtype='<U1')

In [11]:
index, count = np.unique(data, return_counts=True)

In [12]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [13]:
count

array([2, 2, 1], dtype=int64)

In [17]:
result = np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

In [18]:
result

array([0, 2, 3, 1, 0, 0], dtype=int64)

In [19]:
x = np.array([3.14, 2.3, 0, 5, 1.2])

In [20]:
x

array([3.14, 2.3 , 0.  , 5.  , 1.2 ])

In [21]:
result = x.argsort()

In [22]:
result

array([2, 4, 1, 0, 3], dtype=int64)